#!/usr/bin/env python

import sys
import os
refname = sys.argv[0]
oldrev = sys.agrv[1]
newrev = sys.argv[2]
user = os.environ['USER']

print 'Enforcing Policies...'
print refname, oldrev[:6], newrev[:6]
